version: '3.8'
services:
  mongodb:
    image: 'mongo'
    container_name: mongodb
    volumes:
      - data:/data/db
    env_file:
      - ./src/mongodb.env
  app:
    build: ./
    container_name: vaccine-app
    ports:
      - '4000:4000'
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./src/.env
    restart: 'on-failure'
    command: ['npm', 'run', 'dev']
    depends_on:
      - mongodb
volumes:
  data: